export default {
    name: '4v4',

    width: 800,

    height: 350,

    spawnDistance: 350,

    bg: {
        type: 'hockey',
        width: 700,
        height: 320,
        kickOffRadius: 100,
        cornerRadius: 0,
    },

    vertexes: [
        /* 0 */ { x: 701, y: 320, trait: 'ballArea' },
        /* 1 */ { x: 698, y: -317, trait: 'ballArea' },

        /* 2 */ { x: 0, y: 350, trait: 'kickOffBarrier' },
        /* 3 */ {
            x: 0,
            y: 100,
            bCoef: 0.15,
            trait: 'kickOffBarrier',
            color: 'F8F8F8',
            vis: true,
            curve: 180,
        },
        /* 4 */ {
            x: 0,
            y: -100,
            bCoef: 0.15,
            trait: 'kickOffBarrier',
            color: 'F8F8F8',
            vis: true,
            curve: 180,
        },
        /* 5 */ { x: 0, y: -349, trait: 'kickOffBarrier' },

        /* 6 */ {
            x: -701,
            y: -80,
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            curve: 0,
            color: 'F8F8F8',
            pos: [-700, -80],
            p0: [-707.25, 0],
        },
        /* 7 */ {
            x: -740,
            y: -80,
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            curve: 0,
            color: 'F8F8F8',
            pos: [-700, -80],
            p0: [-707.25, 0],
        },
        /* 8 */ {
            x: -740,
            y: 80,
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            curve: 0,
            color: 'F8F8F8',
            pos: [-700, 80],
            p0: [-707.25, 0],
        },
        /* 9 */ {
            x: -701,
            y: 80,
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            curve: 0,
            color: 'F8F8F8',
            pos: [-700, 80],
            p0: [-707.25, 0],
        },
        /* 10 */ {
            x: 699,
            y: -80,
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            curve: 0,
            color: 'F8F8F8',
            pos: [700, -80],
        },
        /* 11 */ {
            x: 740,
            y: -80,
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            curve: 0,
            color: 'F8F8F8',
            pos: [700, -80],
        },
        /* 12 */ {
            x: 740,
            y: 80,
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            curve: 0,
            color: 'F8F8F8',
            pos: [700, 80],
        },
        /* 13 */ {
            x: 699,
            y: 80,
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            curve: 0,
            color: 'F8F8F8',
            pos: [700, 80],
        },

        /* 14 */ {
            x: -700,
            y: 80,
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
            pos: [-700, 80],
            p0: [-707.25, 0],
        },
        /* 15 */ {
            x: -700,
            y: 321,
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
        },
        /* 16 */ {
            x: -700,
            y: -80,
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
            pos: [-700, -80],
            p0: [-707.25, 0],
        },
        /* 17 */ {
            x: -700,
            y: -319,
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
        },
        /* 18 */ {
            x: -700,
            y: 320,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
        },
        /* 19 */ {
            x: 701,
            y: 320,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
        },
        /* 20 */ {
            x: 700,
            y: 80,
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            pos: [700, 80],
        },
        /* 21 */ {
            x: 700,
            y: 320,
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
        },
        /* 22 */ {
            x: 700,
            y: -317,
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
        },
        /* 23 */ {
            x: 700,
            y: -80,
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
            pos: [700, -80],
        },
        /* 24 */ {
            x: 698,
            y: -317,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
        },
        /* 25 */ {
            x: 698,
            y: -317,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
        },
        /* 26 */ {
            x: -701,
            y: -320,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            curve: 0,
        },
        /* 27 */ {
            x: 698,
            y: -320,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            curve: 0,
        },

        /* 28 */ {
            x: 0,
            y: -319,
            bCoef: 0.1,
            cMask: ['red', 'blue'],
            cGroup: ['redKO', 'blueKO'],
            trait: 'kickOffBarrier',
        },
        /* 29 */ {
            x: 0,
            y: -100,
            bCoef: 0.1,
            cMask: ['red', 'blue'],
            cGroup: ['redKO', 'blueKO'],
            trait: 'kickOffBarrier',
        },
        /* 30 */ {
            x: 0,
            y: 100,
            bCoef: 0.1,
            cMask: ['red', 'blue'],
            cGroup: ['redKO', 'blueKO'],
            trait: 'kickOffBarrier',
        },
        /* 31 */ {
            x: 0,
            y: 320,
            bCoef: 0.1,
            cMask: ['red', 'blue'],
            cGroup: ['redKO', 'blueKO'],
            trait: 'kickOffBarrier',
        },
        /* 32 */ {
            x: 0,
            y: -100,
            bCoef: 0.1,
            cMask: ['red', 'blue'],
            trait: 'kickOffBarrier',
            vis: true,
            color: 'F8F8F8',
        },
        /* 33 */ {
            x: 0,
            y: 100,
            bCoef: 0.1,
            cMask: ['red', 'blue'],
            trait: 'kickOffBarrier',
            vis: true,
            color: 'F8F8F8',
        },
        /* 34 */ {
            x: 0,
            y: 100,
            trait: 'kickOffBarrier',
            color: 'F8F8F8',
            vis: true,
            curve: -180,
        },
        /* 35 */ {
            x: 0,
            y: -100,
            trait: 'kickOffBarrier',
            color: 'F8F8F8',
            vis: true,
            curve: -180,
        },
        /* 36 */ {
            x: 0,
            y: 100,
            trait: 'kickOffBarrier',
            color: 'F8F8F8',
            vis: true,
            curve: 0,
        },
        /* 37 */ {
            x: 0,
            y: -100,
            trait: 'kickOffBarrier',
            color: 'F8F8F8',
            vis: true,
            curve: 0,
        },

        /* 38 */ {
            x: -707.5,
            y: 80,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            curve: 0,
            vis: false,
            pos: [-700, 80],
            p0: [-707.25, 0],
        },
        /* 39 */ {
            x: -707.5,
            y: 321,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            curve: 0,
            vis: false,
        },
        /* 40 */ {
            x: -707.5,
            y: -320,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            vis: false,
            curve: 0,
        },
        /* 41 */ {
            x: -707.5,
            y: -81,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            vis: false,
            curve: 0,
            pos: [-700, -80],
            p0: [-707.25, 0],
        },
        /* 42 */ {
            x: 707.5,
            y: -319,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            vis: false,
            curve: 0,
        },
        /* 43 */ {
            x: 707.5,
            y: -82,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            vis: false,
            curve: 0,
            pos: [700, -80],
        },
        /* 44 */ {
            x: 707.5,
            y: 81,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            curve: 0,
            vis: false,
            pos: [700, 80],
        },
        /* 45 */ {
            x: 707.5,
            y: 321,
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            curve: 0,
            vis: false,
        },

        /* 46 */ { x: 0, y: -100, bCoef: 0.1, trait: 'line' },
        /* 47 */ { x: 0, y: 100, bCoef: 0.1, trait: 'line' },
        /* 48 */ {
            x: -700,
            y: -80,
            bCoef: 0.1,
            trait: 'line',
            p0: [-707.25, 0],
        },
        /* 49 */ {
            x: -700,
            y: 80,
            bCoef: 0.1,
            trait: 'line',
            p0: [-707.25, 0],
        },
        /* 50 */ { x: 700, y: -80, bCoef: 0.1, trait: 'line' },
        /* 51 */ { x: 700, y: 80, bCoef: 0.1, trait: 'line' },
        /* 52 */ {
            x: -700,
            y: 270,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: -90,
        },
        /* 53 */ {
            x: -470,
            y: 65,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: 0,
        },
        /* 54 */ { x: -700, y: 307, bCoef: 0.1, trait: 'line', curve: -90 },
        /* 55 */ { x: -686, y: 320, bCoef: 0.1, trait: 'line', curve: -90 },
        /* 56 */ {
            x: -700,
            y: -270,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: 90,
        },
        /* 57 */ {
            x: -470,
            y: -75,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: 0,
        },
        /* 58 */ { x: -700, y: -305, bCoef: 0.1, trait: 'line', curve: 90 },
        /* 59 */ { x: -687, y: -320, bCoef: 0.1, trait: 'line', curve: 90 },
        /* 60 */ { x: 700, y: -303, bCoef: 0.1, trait: 'line', curve: -90 },
        /* 61 */ { x: 684, y: -320, bCoef: 0.1, trait: 'line', curve: -90 },
        /* 62 */ { x: 700, y: 306, bCoef: 0.1, trait: 'line', curve: 90 },
        /* 63 */ { x: 687, y: 320, bCoef: 0.1, trait: 'line', curve: 90 },
        /* 64 */ {
            x: 700,
            y: 270,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: 90,
        },
        /* 65 */ {
            x: 470,
            y: 66,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: 90,
        },
        /* 66 */ {
            x: 700,
            y: -270,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: -90,
        },
        /* 67 */ {
            x: 470,
            y: -74,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: -90,
        },
        /* 68 */ {
            x: 470,
            y: 66,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: 0,
        },
        /* 69 */ {
            x: 470,
            y: -74,
            bCoef: 0.1,
            trait: 'line',
            color: 'F8F8F8',
            curve: 0,
        },
        /* 70 */ { x: -414, y: -3, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 71 */ { x: -414, y: -5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 72 */ { x: -414, y: -1, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 73 */ { x: -414, y: -7, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 74 */ { x: -414, y: -6, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 75 */ { x: -414, y: -2, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 76 */ { x: -414, y: -7.5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 77 */ { x: -414, y: -0.5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 78 */ { x: 398, y: -1, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 79 */ { x: 398, y: -3, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 80 */ { x: 398, y: 1, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 81 */ { x: 398, y: -5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 82 */ { x: 398, y: -4, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 83 */ { x: 398, y: 0, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 84 */ { x: 398, y: -5.5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 85 */ { x: 398, y: 1.5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 86 */ { x: -316.5, y: -3, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 87 */ { x: -316.5, y: -5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 88 */ { x: -316.5, y: -1, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 89 */ { x: -316.5, y: -7, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 90 */ { x: -316.5, y: -6, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 91 */ { x: -316.5, y: -2, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 92 */ { x: -316.5, y: -7.5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 93 */ { x: -316.5, y: -0.5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 94 */ { x: 300.5, y: -1, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 95 */ { x: 300.5, y: -3, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 96 */ { x: 300.5, y: 1, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 97 */ { x: 300.5, y: -5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 98 */ { x: 300.5, y: -4, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 99 */ { x: 300.5, y: 0, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 100 */ { x: 300.5, y: -5.5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 101 */ { x: 300.5, y: 1.5, bCoef: 0.1, trait: 'line', curve: 180 },
        /* 102 */ { x: -246, y: 305, bCoef: 0.1, trait: 'line' },
        /* 103 */ { x: -246, y: 335, bCoef: 0.1, trait: 'line' },
        /* 104 */ { x: -126, y: 305, bCoef: 0.1, trait: 'line' },
        /* 105 */ { x: -126, y: 335, bCoef: 0.1, trait: 'line' },
        /* 106 */ { x: 246, y: 305, bCoef: 0.1, trait: 'line' },
        /* 107 */ { x: 246, y: 335, bCoef: 0.1, trait: 'line' },
        /* 108 */ { x: 126, y: 305, bCoef: 0.1, trait: 'line' },
        /* 109 */ { x: 126, y: 335, bCoef: 0.1, trait: 'line' },
        /* 110 */ { x: -387, y: 320, bCoef: 0.1, trait: 'line' },
        /* 111 */ { x: -387, y: 337, bCoef: 0.1, trait: 'line' },
        /* 112 */ {
            x: -706,
            y: 123,
            bCoef: 0.1,
            trait: 'line',
            p0: [-707.25, 0],
        },
        /* 113 */ {
            x: -726,
            y: 123,
            bCoef: 0.1,
            trait: 'line',
            p0: [-707.25, 0],
        },
        /* 114 */ { x: 706, y: 123, bCoef: 0.1, trait: 'line' },
        /* 115 */ { x: 724, y: 123, bCoef: 0.1, trait: 'line' },
        /* 116 */ {
            x: -706,
            y: -123,
            bCoef: 0.1,
            trait: 'line',
            p0: [-707.25, 0],
        },
        /* 117 */ {
            x: -726,
            y: -123,
            bCoef: 0.1,
            trait: 'line',
            p0: [-707.25, 0],
        },
        /* 118 */ { x: 706, y: -123, bCoef: 0.1, trait: 'line' },
        /* 119 */ { x: 724, y: -123, bCoef: 0.1, trait: 'line' },
        /* 120 */ { x: -380, y: -320, bCoef: 0.1, trait: 'line' },
        /* 121 */ { x: -380, y: -337, bCoef: 0.1, trait: 'line' },
        /* 122 */ { x: 380, y: 320, bCoef: 0.1, trait: 'line' },
        /* 123 */ { x: 380, y: 337, bCoef: 0.1, trait: 'line' },
        /* 124 */ { x: 380, y: -320, bCoef: 0.1, trait: 'line' },
        /* 125 */ { x: 380, y: -337, bCoef: 0.1, trait: 'line' },

        /* 126 */ {
            x: 703,
            y: -319,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
            vis: false,
            curve: 0,
        },
        /* 127 */ {
            x: 703,
            y: -82,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
            pos: [700, -80],
            vis: false,
            curve: 0,
        },
        /* 128 */ {
            x: 703,
            y: 81,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            pos: [700, 80],
            vis: false,
            curve: 0,
        },
        /* 129 */ {
            x: 703,
            y: 321,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            vis: false,
            curve: 0,
        },
        /* 130 */ {
            x: -703,
            y: 78,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
            pos: [-700, 80],
            vis: false,
            p0: [-707.25, 0],
        },
        /* 131 */ {
            x: -703,
            y: 319,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
            vis: false,
        },
        /* 132 */ {
            x: -703,
            y: -82,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
            pos: [-700, -80],
            vis: false,
            p0: [-707.25, 0],
        },
        /* 133 */ {
            x: -703,
            y: -321,
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            color: 'F8F8F8',
            vis: false,
        },
    ],

    segments: [
        {
            v0: 6,
            v1: 7,
            curve: 0,
            color: 'F8F8F8',
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            pos: [-700, -80],
            y: -80,
            p0: [-707.25, 0],
        },
        {
            v0: 7,
            v1: 8,
            color: 'F8F8F8',
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            x: -740,
            p0: [-707.25, 0],
        },
        {
            v0: 8,
            v1: 9,
            curve: 0,
            color: 'F8F8F8',
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            pos: [-700, 80],
            y: 80,
            p0: [-707.25, 0],
        },
        {
            v0: 10,
            v1: 11,
            curve: 0,
            color: 'F8F8F8',
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            pos: [700, -80],
            y: -80,
        },
        {
            v0: 11,
            v1: 12,
            color: 'F8F8F8',
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            x: 740,
        },
        {
            v0: 12,
            v1: 13,
            curve: 0,
            color: 'F8F8F8',
            cMask: ['red', 'blue', 'ball'],
            trait: 'goalNet',
            pos: [700, 80],
            y: 80,
        },

        { v0: 2, v1: 3, trait: 'kickOffBarrier' },
        {
            v0: 3,
            v1: 4,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.15,
            cGroup: ['blueKO'],
            trait: 'kickOffBarrier',
        },
        {
            v0: 3,
            v1: 4,
            curve: -180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.15,
            cGroup: ['redKO'],
            trait: 'kickOffBarrier',
        },
        { v0: 4, v1: 5, trait: 'kickOffBarrier' },

        {
            v0: 14,
            v1: 15,
            vis: true,
            color: 'F8F8F8',
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            x: -700,
        },
        {
            v0: 16,
            v1: 17,
            vis: true,
            color: 'F8F8F8',
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            x: -700,
        },
        {
            v0: 18,
            v1: 19,
            vis: true,
            color: 'F8F8F8',
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            y: 320,
        },
        {
            v0: 20,
            v1: 21,
            vis: true,
            color: 'F8F8F8',
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            x: 700,
        },
        {
            v0: 22,
            v1: 23,
            vis: true,
            color: 'F8F8F8',
            bCoef: 1.15,
            cMask: ['ball'],
            trait: 'ballArea',
            x: 700,
        },
        {
            v0: 24,
            v1: 25,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            x: 550,
            y: -240,
        },
        {
            v0: 26,
            v1: 27,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            y: -320,
        },

        {
            v0: 28,
            v1: 29,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            cMask: ['red', 'blue'],
            cGroup: ['redKO', 'blueKO'],
            trait: 'kickOffBarrier',
        },
        {
            v0: 30,
            v1: 31,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            cMask: ['red', 'blue'],
            cGroup: ['redKO', 'blueKO'],
            trait: 'kickOffBarrier',
        },

        {
            v0: 38,
            v1: 39,
            curve: 0,
            vis: false,
            color: 'F8F8F8',
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            x: -707.5,
        },
        {
            v0: 40,
            v1: 41,
            curve: 0,
            vis: false,
            color: 'F8F8F8',
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            x: -707.5,
        },
        {
            v0: 42,
            v1: 43,
            curve: 0,
            vis: false,
            color: 'F8F8F8',
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            x: 707.5,
        },
        {
            v0: 44,
            v1: 45,
            curve: 0,
            vis: false,
            color: 'F8F8F8',
            bCoef: 1,
            cMask: ['ball'],
            trait: 'ballArea',
            x: 707.5,
        },

        {
            v0: 46,
            v1: 47,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 0,
        },
        {
            v0: 48,
            v1: 49,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -700,
            p0: [-707.25, 0],
        },
        {
            v0: 50,
            v1: 51,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 700,
        },
        {
            v0: 52,
            v1: 53,
            curve: -90,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            v0: 55,
            v1: 54,
            curve: -90,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            v0: 56,
            v1: 57,
            curve: 90,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            v0: 53,
            v1: 57,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -470,
        },
        {
            v0: 59,
            v1: 58,
            curve: 90,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            v0: 61,
            v1: 60,
            curve: -90,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            v0: 63,
            v1: 62,
            curve: 90,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            v0: 64,
            v1: 65,
            curve: 90,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            v0: 66,
            v1: 67,
            curve: -90,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            v0: 68,
            v1: 69,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 470,
        },
        {
            v0: 71,
            v1: 70,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -375,
        },
        {
            v0: 70,
            v1: 71,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -375,
        },
        {
            v0: 73,
            v1: 72,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -375,
        },
        {
            v0: 72,
            v1: 73,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -375,
        },
        {
            v0: 75,
            v1: 74,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -375,
        },
        {
            v0: 74,
            v1: 75,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -375,
        },
        {
            v0: 77,
            v1: 76,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -375,
        },
        {
            v0: 76,
            v1: 77,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -375,
        },
        {
            v0: 79,
            v1: 78,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 375,
        },
        {
            v0: 78,
            v1: 79,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 375,
        },
        {
            v0: 81,
            v1: 80,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 375,
        },
        {
            v0: 80,
            v1: 81,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 375,
        },
        {
            v0: 83,
            v1: 82,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 375,
        },
        {
            v0: 82,
            v1: 83,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 375,
        },
        {
            v0: 85,
            v1: 84,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 375,
        },
        {
            v0: 84,
            v1: 85,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 375,
        },
        {
            v0: 87,
            v1: 86,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -277.5,
        },
        {
            v0: 86,
            v1: 87,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -277.5,
        },
        {
            v0: 89,
            v1: 88,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -277.5,
        },
        {
            v0: 88,
            v1: 89,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -277.5,
        },
        {
            v0: 91,
            v1: 90,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -277.5,
        },
        {
            v0: 90,
            v1: 91,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -277.5,
        },
        {
            v0: 93,
            v1: 92,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -277.5,
        },
        {
            v0: 92,
            v1: 93,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -277.5,
        },
        {
            v0: 95,
            v1: 94,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 277.5,
        },
        {
            v0: 94,
            v1: 95,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 277.5,
        },
        {
            v0: 97,
            v1: 96,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 277.5,
        },
        {
            v0: 96,
            v1: 97,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 277.5,
        },
        {
            v0: 99,
            v1: 98,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 277.5,
        },
        {
            v0: 98,
            v1: 99,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 277.5,
        },
        {
            v0: 101,
            v1: 100,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 277.5,
        },
        {
            v0: 100,
            v1: 101,
            curve: 180,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 277.5,
        },
        {
            v0: 102,
            v1: 103,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -240,
        },
        {
            v0: 104,
            v1: 105,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -120,
        },
        {
            v0: 106,
            v1: 107,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 240,
        },
        {
            v0: 108,
            v1: 109,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 120,
        },
        {
            v0: 110,
            v1: 111,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -381,
        },
        {
            v0: 112,
            v1: 113,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -240,
            y: 123,
            p0: [-707.25, 0],
        },
        {
            v0: 114,
            v1: 115,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -240,
            y: 123,
        },
        {
            v0: 116,
            v1: 117,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -240,
            y: -123,
            p0: [-707.25, 0],
        },
        {
            v0: 118,
            v1: 119,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -240,
            y: -123,
        },
        {
            v0: 120,
            v1: 121,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: -380,
        },
        {
            v0: 122,
            v1: 123,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 380,
        },
        {
            v0: 124,
            v1: 125,
            curve: 0,
            vis: true,
            color: 'F8F8F8',
            bCoef: 0.1,
            trait: 'line',
            x: 380,
        },

        {
            v0: 126,
            v1: 127,
            vis: false,
            color: 'F8F8F8',
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            x: 703,
            curve: 0,
        },
        {
            v0: 128,
            v1: 129,
            vis: false,
            color: 'F8F8F8',
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            x: 703,
            curve: 0,
        },
        {
            v0: 130,
            v1: 131,
            vis: false,
            color: 'F8F8F8',
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            x: -703,
        },
        {
            v0: 132,
            v1: 133,
            vis: false,
            color: 'F8F8F8',
            bCoef: 0,
            cMask: ['ball'],
            trait: 'ballArea',
            x: -703,
        },
    ],

    goals: [
        { p0: [-706.25, 80], p1: [-706.25, -75], team: 'red' },
        { p0: [706.25, 80], p1: [706.25, -75], team: 'blue' },
    ],

    discs: [
        {
            radius: 5,
            pos: [-700, 80],
            color: '6666CC',
            trait: 'goalPost',
            y: 80,
            p0: [-707.25, 0],
        },
        {
            radius: 5,
            pos: [-700, -80],
            color: '6666CC',
            trait: 'goalPost',
            y: -80,
            x: -560,
            p0: [-707.25, 0],
        },
        {
            radius: 5,
            pos: [700, 80],
            color: '6666CC',
            trait: 'goalPost',
            y: 80,
        },
        {
            radius: 5,
            pos: [700, -80],
            color: '6666CC',
            trait: 'goalPost',
            y: -80,
        },

        {
            radius: 3,
            invMass: 0,
            pos: [-700, 320],
            color: 'FFCC00',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            radius: 3,
            invMass: 0,
            pos: [-700, -320],
            color: 'FFCC00',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            radius: 3,
            invMass: 0,
            pos: [700, -320],
            color: 'FFCC00',
            bCoef: 0.1,
            trait: 'line',
        },
        {
            radius: 3,
            invMass: 0,
            pos: [700, 320],
            color: 'FFCC00',
            bCoef: 0.1,
            trait: 'line',
        },
    ],

    planes: [
        {
            normal: [0, 1],
            dist: -320,
            bCoef: 1,
            trait: 'ballArea',
            vis: false,
            curve: 0,
        },
        { normal: [0, -1], dist: -320, bCoef: 1, trait: 'ballArea' },

        { normal: [0, 1], dist: -350, bCoef: 0.1 },
        { normal: [0, -1], dist: -350, bCoef: 0.1 },
        { normal: [1, 0], dist: -760, bCoef: 0.1 },
        { normal: [-1, 0], dist: -760, bCoef: 0.1 },

        {
            normal: [1, 0],
            dist: -760,
            bCoef: 0.1,
            trait: 'ballArea',
            vis: false,
            curve: 0,
        },
        {
            normal: [-1, 0],
            dist: -760,
            bCoef: 0.1,
            trait: 'ballArea',
            vis: false,
            curve: 0,
        },
    ],

    traits: {
        ballArea: { vis: false, bCoef: 1, cMask: ['ball'] },
        goalPost: { radius: 8, invMass: 0, bCoef: 0.5 },
        goalNet: { vis: true, bCoef: 0.1, cMask: ['ball'] },
        line: { vis: true, bCoef: 0.1, cMask: [''] },
        kickOffBarrier: {
            vis: false,
            bCoef: 0.1,
            cGroup: ['redKO', 'blueKO'],
            cMask: ['red', 'blue'],
        },
    },

    playerPhysics: {
        bCoef: 0,
        acceleration: 0.11,
        kickingAcceleration: 0.083,
        kickStrength: 5,
    },

    ballPhysics: {
        radius: 6.25,
        bCoef: 0.4,
        invMass: 1.5,
        damping: 0.99,
        color: 'FFCC00',
    },
}
